### ISSUE TITLE
pudb isn't compatible w/ mercurial.demandimport

### ISSUE THREAD

**Issue by jsoref** [inducer/pudb#177]
Mercurial has a magical import wrapper called demandimport.

```py
import mercurial
import mercurial.demandimport
mercurial.demandimport.enable()
import foo
```

if foo does not exist, it will not throw an exception at this point.
Instead, it will throw its exception when you do:

```py
foo.bar
```

I realized this when using **py3** (not **IronPython**) w/ mercurial.demandimport and **pudb3**:
```py
>>> ctypes.util                                                                                    
Traceback (most recent call last):                                                                 
  File "/home/timeless/hg/py3/lib/python3.5/site-packages/pudb/debugger.py", line 1415, in         
cmdline_get_namespace                                                                              
    from pudb.shell import SetPropagatingDict                                                      
  File "/home/timeless/hg/crew/mercurial/demandimport.py", line 143, in _demandimport              
    return _hgextimport(_import, name, globals, locals, fromlist, level)                           
  File "/home/timeless/hg/crew/mercurial/demandimport.py", line 53, in _hgextimport                
    return importfunc(name, globals, *args, **kwargs)                                              
  File "/home/timeless/hg/py3/lib/python3.5/site-packages/pudb/shell.py", line 183, in <module>    
    if HAVE_IPYTHON and hasattr(IPython, 'Shell'):                                                 
  File "/home/timeless/hg/crew/mercurial/demandimport.py", line 132, in __getattribute__           
    self._load()                                                                                   
  File "/home/timeless/hg/crew/mercurial/demandimport.py", line 98, in _load                       
    mod = _hgextimport(_import, head, globals, locals, None, level)                                
  File "/home/timeless/hg/crew/mercurial/demandimport.py", line 53, in _hgextimport                
    return importfunc(name, globals, *args, **kwargs)                                              
ImportError: No module named 'IPython'                                                             
```

The fix for this sort of thing is to access a property of each module inside the try block that intends to import the module. I'll try to write a PR for this, but first I'll need to find out what properties IPython has (and probably try installing it...

**Comment by asmeurer** [comment]
Your fix sounds simple enough, and I wouldn't be opposed to accepting it, but it seems to me that this should be a mercurial bug. [demandimport](https://github.com/ajaxorg/mercurial/blob/master/mercurial/demandimport.py) uses some devious magic (it overwrites the `__import__` builtin, meaning all import statements everywhere use its magic). I see the value of this sort of magic (or at least the perceived value :), but why does it apply this magic globally? It makes more sense for `mercurial.demandimport.enable()` to either take `__name__`  as an argument or use some frame magic to only apply itself to the module (or at least top-level module) that calls the function. Otherwise you have behavior like this where a completely unrelated module like pudb makes some assumptions about how import normally works that fail for demandimport. But pudb wasn't ever designed to work with delayed importing (nor does it need it). I imagine there are tons of other Python modules that would similarly break.
