### ISSUE TITLE
pudb3 crashes when you enter ipdb in post-mortem mode

### ISSUE THREAD

**Issue by varmanishant** [inducer/pudb#182]
Just run a script, click on 'Examine' and enter post-mortem mode. Enter iPython using `!`. One ou are in iPython quit it using <kbd>Ctrl-D</kbd> , it will show a list index out of range error. You can make it work with a try except, however can this be handled more correctly?

**Comment by asmeurer** [comment]
I can reproduce the error. I don't understand what that code is doing, though. Catching the exception and returning a dummy value doesn't seem to break anything obvious. This is the traceback

```pytb
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/bin/pudb", line 6, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/Documents/pudb/pudb/run.py", line 30, in main
    steal_output=options.steal_output)
  File "/Users/aaronmeurer/Documents/pudb/pudb/__init__.py", line 121, in runscript
    dbg.interaction(None, sys.exc_info(), show_exc_dialog=False)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 339, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 2059, in call_with_ui
    return f(*args, **kwargs)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 2272, in interaction
    self.event_loop()
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 2238, in event_loop
    toplevel.keypress(self.size, k)
  File "/Users/aaronmeurer/Documents/pudb/pudb/ui_tools.py", line 100, in keypress
    return handler(self, size, key)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 1777, in run_cmdline
    return run_external_cmdline(w, size, key)
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 1771, in run_external_cmdline
    self.update_var_view()
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 2315, in update_var_view
    self.get_frame_var_info(read_only=True),
  File "/Users/aaronmeurer/Documents/pudb/pudb/var_view.py", line 531, in get_frame_var_info
    ssid = self.debugger.get_stack_situation_id()
  File "/Users/aaronmeurer/Documents/pudb/pudb/debugger.py", line 342, in get_stack_situation_id
    return str(id(self.stack[self.curindex][0].f_code))
IndexError: list index out of range
```

What is a stack_situation_id?
