### ISSUE TITLE
Problems when setting breakpoints

### ISSUE THREAD

**Issue by enmy211** [inducer/pudb#223]
When I try to set a breakpoin, I get the errormessage:
**The breakpoint you just set may be invalid, for the following reason:
File failed to compile.**

I can set breakpoint with _Set Anyway_. After some debugging, the breakpoint(s) disappear.

Version of pudb is 2017.1, python 2.7.12+ and Ubuntu 16.10.

Eivind

**Comment by asmeurer** [comment]
It means you have a breakpoint in a file that isn't valid Python. Maybe it's a saved breakpoint?

**Comment by enmy211** [comment]
Thank you for your quick reply!

I have tested pudb on several files and the error still occour.

Som files everything just works, and I can't find out what may cause the 
error. There is no hidden signs in file (vim, :set list).

But I discovered something interesting: When I test on a file that 
everything works and when I try to set a breakpoint at a blank line, I 
get the same error.

It is not a saved breakpoint.

I have tested the same files (with error), with pdb and that is ok.

When I had an earlier version of pudb there were no such error (I have 
reinstalled my machine)


Den 15. feb. 2017 09:03, skrev Aaron Meurer:

**Comment by asmeurer** [comment]
Which version is the old version (it's in the upper left)?

**Comment by enmy211** [comment]
I started on version 2015.4 and upgraded to version 2016.1. There was no errors then.

**Comment by enmy211** [comment]
For information: I have installed pudb on _user_.  _pip -install --user --upgrade pudb_

**Comment by enmy211** [comment]
I installed version 2016.1 in a virtualenv and no errors.

**Comment by asmeurer** [comment]
If it works in a virtualenv then maybe your user installation is broken.

**Comment by enmy211** [comment]
I've tested pudb version 2016.1 in virtualenv with no errors.
I've just now tested pudb version 2017.1 in virtualenv, with same errors.

I don't think it is my user installation that is broken.
To be sure, this weekend I will install ubuntu on a virtualbox and test an installation there.

**Comment by enmy211** [comment]
I've tested pudb on Ubuntu 16.10, installed on VirtualBox and I get the same error. 
I bypass the problem with pudb 2016.1.

I hope there will be a fix for this, because I am very addicted to pudb.

**Comment by asmeurer** [comment]
It always happens with the same file, or it happens with any file?

**Comment by enmy211** [comment]
It happens almost in every file, but a very few it is ok.

I have checked every character in the files, by looping through them by 
a script, and I cant find anything that seems to trigger the error.

I've attached two files:

     test.py which pudb is ok.

     ny_pub_tst.py which trigger the error.


Den 17. feb. 2017 16:53, skrev Aaron Meurer:

**Comment by asmeurer** [comment]
File attachments don't work on GitHub issues. Can you paste the files in a gist?

**Comment by enmy211** [comment]
I'm sorry, I just replied by e-mail.
I've created a gist which contains these two files.

**Comment by enmy211** [comment]
I also found an another error, _UnicodeDecodeError_

`if linje.Inf81 in lstAktuelleVaregrupper:
`

_linje.Inf81_ is a cellvalue in a pandas.DataFrame and contains "NØS"


**Stacktrace**

Traceback (most recent call last):
  File "rodin_test_import.py", line 47, in <module>
    if linje.Inf81 in lstAktuelleVaregrupper:
  File "rodin_test_import.py", line 47, in <module>
    if linje.Inf81 in lstAktuelleVaregrupper:
  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 173, in dispatch_line
    self.user_line(frame)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 371, in user_line
    self.interaction(frame)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 339, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2079, in call_with_ui
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2299, in interaction
    self.event_loop()
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2257, in event_loop
    canvas = toplevel.render(self.size, focus=True)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 2085, in render
    focus = focus and self.focus_position == i)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1526, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1526, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/listbox.py", line 475, in render
    focus_canvas = focus_widget.render((maxcol,), focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/pudb/var_view.py", line 163, in render
    return make_canvas(text, attr, maxcol, apfx+"value")
  File "/usr/local/lib/python2.7/dist-packages/pudb/ui_tools.py", line 38, in make_canvas
    line_attr = list(get_byte_line_attr(line, line_attr))
  File "/usr/local/lib/python2.7/dist-packages/pudb/ui_tools.py", line 34, in get_byte_line_attr
    byte_count = len(line[i:i+column_count].encode(_target_encoding))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

**Comment by asmeurer** [comment]
What does

```py
from urwid.util import _target_encoding
print(_target_encoding)
```

give for you?

**Comment by enmy211** [comment]
That gives me: *utf-8*


Den 21. feb. 2017 19:49, skrev Aaron Meurer:

**Comment by enmy211** [comment]
I replied by e-mail and I used bold, and it translated to `*utf-8*` , but it gives me just `utf-8`

**Comment by asmeurer** [comment]
I don't understand why it's using the ASCII codec then.

**Comment by enmy211** [comment]
Sorry to bother you with this. It's a standard "fault" in python.

Solved it with:
`import sys
reload(sys); 
sys.setdefaultencoding('utf-8')`

**Comment by asmeurer** [comment]
I'm sure this is some Python 2 thing. I'm not too familiar with how Python 2 handles this stuff. Maybe if someone else knows more, they can say if there is some change that needs to be made to PuDB or not.

**Comment by enmy211** [comment]
I have now started to convert to python 3.5.
I've tested pudb on python 3.5 and there is **no error**.
Python > 3.x is the future so I think we should close this thread. OK?
