### ISSUE TITLE
How to use multi-line python commands in the Command Area

### ISSUE THREAD

**Issue by fotwo** [inducer/pudb#296]
Hi, all. How to use multi-line python commands in the Command Area? For example, if I want to use 'for-loop' in the Command Area, what should I do? Thanks.

**Comment by asmeurer** [comment]
Looks like `compile('single')` isn't useful by itself. You have to use the stuff in the `codeop` module, or better, the stuff in the `code` module. The PuDB shell should probably be redone to subclass `code.InteractiveConsole` (see https://github.com/python/cpython/blob/3.6/Lib/code.py).

**Comment by fotwo** [comment]
I tried the method like this:
`import code`
`code.interact(local=vars())`
then, it showed the message
"
Traceback (most recent call last):                           
  File "<pudb command line>", line 1, in <module>            
  File "/usr/lib64/python2.7/code.py", line 306, in interact 
    console.interact(banner)                                 
  File "/usr/lib64/python2.7/code.py", line 234, in interact 
    line = self.raw_input(prompt)                            
  File "/usr/lib64/python2.7/code.py", line 281, in raw_input
    return raw_input(prompt)                                 
AttributeError: 'NoneType' object has no attribute 'readline'
Python 2.7.5 (default, Nov  6 2016, 00:28:07)                
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2            
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
"
It looks like the "interactive module" launched successfully, while I still cannot use 'for-loop' command like:
`a=[1,2,3]`
`for i in a:`

**Comment by fotwo** [comment]
Actually, I use pudb in a vitual environment built via 'virtualenv'. Is it the reason?

**Comment by asmeurer** [comment]
My comment was about how to fix the bug, not a workaround. I don't think there is any way presently to do this. If you want to use multiline statements, you'll need to use an external shell (press `!`).

**Comment by AllanLRH** [comment]
I'd also suggest using the external shell — it's gives you a much larger working area, which is something that I like to have, if I write code spanning multiple lines... especially since you're likely to print out values in a debugging session?

Be sure to chose an environment you prefer for the external shell — I use the Ipython shell, but there's a few other options as well.

**Comment by fotwo** [comment]
Thanks @AllanLRH and @asmeurer , the external shell can meet my need. I close this issue.

**Comment by asmeurer** [comment]
This issue is still valid. Multiline should be made to work in the built in shell.
