### ISSUE TITLE
Is there a way to goto a file?

### ISSUE THREAD

**Issue by alok** [inducer/pudb#299]
I see that you can open any module, but the ability to jump to an arbitrary file and mark it for breakpoints would nice.

**Comment by inducer** [comment]
Could you explain the use case? How would the flow of execution get there?

**Comment by Alok** [comment]
It's handy for setting breakpoints on the fly.

In my latest real-world use case, there's a conditional import nested deep in the code and I want to set a breakpoint to step through which import is sourced. It'd be nice to be able to do this in PUDB from one session rather than opening the file in pudb in another terminal and setting it.

**Comment by inducer** [comment]
You can already get to any importable file, not just ones that are already imported. Not sure I understand what you mean.

**Comment by NewtoAI** [comment]
is it possible or supported? 
(SCEN 1)
I set breakpoint using pudb on a file say (eval.py)
(1) then I run my application without using pudb
--> The file with breakpoint automatically opens up on reaching eval.py in execution

(SCEN 2)
I set breakpoint using pudb on a file say (eval.py)
(2) I run my application using pudb lets say 

pudb: <myfile.py> <argument inputs to myfile.py>   //Is this supported ?

(3) pudb doesnt open debug window rightaway but only opens it when it encounters eval.py during the run


Is it possible ?

**Comment by inducer** [comment]
@NewtoAI: I'm deleting your comment (and this one) because

* You chose to clutter up a focused bug report with unrelated/semi-related support questions, which is unfriendly.

* This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

**Comment by astier** [comment]
@inducer How can I go to any importable file from within pudb? I also have often usecases where I start the debugger in my main-file and during the debugging-session I want to set a breakpoint in another file. However, I can figure out how to do it.

**Comment by inducer** [comment]
@astier Hit `m` from the main screen of the debugger, enter the module name.

**Comment by astier** [comment]
This results in an exception.
```
Traceback (most recent call last):
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/run.py", line 38, in <module>
    main()
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/run.py", line 34, in main
    steal_output=options.steal_output)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/__init__.py", line 126, in runscript
    dbg.interaction(None, sys.exc_info())
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/debugger.py", line 376, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/debugger.py", line 2118, in call_with_ui
    return f(*args, **kwargs)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/debugger.py", line 2362, in interaction
    self.event_loop()
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/debugger.py", line 2328, in event_loop
    toplevel.keypress(self.size, k)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/ui_tools.py", line 106, in keypress
    result = self._w.keypress(size, key)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/urwid/container.py", line 1590, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/ui_tools.py", line 111, in keypress
    return handler(self, size, key)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/debugger.py", line 1355, in pick_module
    build_filtered_mod_list(filt_edit.get_edit_text()))
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/debugger.py", line 1319, in build_filtered_mod_list
    for name, mod in list(sys.modules.items())
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/debugger.py", line 1320, in <genexpr>
    if mod_exists(mod))
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/site-packages/pudb/debugger.py", line 1301, in mod_exists
    base, ext = splitext(filename)
  File "/home/aleks/miniconda3/envs/mdp/lib/python3.7/posixpath.py", line 122, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by astier** [comment]
I opened an issue #327

**Comment by inducer** [comment]
It seems like this is resolved. Closing, please speak up if there are still remaining concerns.
