### ISSUE TITLE
ImportError: cannot import name 'CONFIG'

### ISSUE THREAD

**Issue by jbagot** [inducer/pudb#325]
I installed the package with `pip install pudb` in a virtualenv in a ubuntu laptop.
I add the line `import pudb; pudb.set_trace()` in my code and then I executed my python project. Then I receive this error: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/.../venv/lib/python3.6/site-packages/pudb/run.py", line 38, in <module>
    main()
  File "/home/.../venv/lib/python3.6/site-packages/pudb/run.py", line 34, in main
    steal_output=options.steal_output)
  File "/home/.../venv/lib/python3.6/site-packages/pudb/__init__.py", line 90, in runscript
    dbg = _get_debugger(steal_output=steal_output)
  File "/home/.../venv/lib/python3.6/site-packages/pudb/__init__.py", line 75, in _get_debugger
    from pudb.debugger import Debugger
  File "/home/.../venv/lib/python3.6/site-packages/pudb/debugger.py", line 19, in <module>
    from pudb.var_view import FrameVarInfoKeeper
  File "/home/.../venv/lib/python3.6/site-packages/pudb/var_view.py", line 6, in <module>
    from pudb.debugger import CONFIG
ImportError: cannot import name 'CONFIG'
```
I checked the file and I saw that tries to find some configuration file in some directories defined in `XDG_CONFIG_DIRS` but I don't have any file of pudb there.

Any idea? I use pudb in other projects and works fine. Have I to add some flag?

**Comment by inducer** [comment]
There seems to be an import cycle there--I wonder why the code even worked for me. Could you try the latest git and see if that makes things better?
