### ISSUE TITLE
Python 2 repr with non-ascii bytes crashes pudb

### ISSUE THREAD

**Issue by jordigh** [inducer/pudb#338]
Sample file

```python
#encoding: utf-8

import pudb

class X(object):
    def __repr__(self):
        return u"lól".encode('utf8')

x = X()
    
pu.db
```

In Python 2, I believe repr should return encoded bytes, not unicode strings. When I run the above in Python 2, I get the following stack trace:

```
$ python foo.py 
Traceback (most recent call last):
  File "foo.py", line 11, in <module>
    pu.db
  File "/usr/lib/python2.7/bdb.py", line 53, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/lib/python2.7/bdb.py", line 88, in dispatch_return
    self.user_return(frame, arg)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/pudb/debugger.py", line 425, in user_return
    self.interaction(frame)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/pudb/debugger.py", line 378, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/pudb/debugger.py", line 2147, in call_with_ui
    return f(*args, **kwargs)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/pudb/debugger.py", line 2399, in interaction
    self.event_loop()
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/pudb/debugger.py", line 2357, in event_loop
    canvas = toplevel.render(self.size, focus=True)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 1765, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/container.py", line 2087, in render
    focus = focus and self.focus_position == i)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 1765, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/container.py", line 1529, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/container.py", line 1529, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 1765, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/listbox.py", line 501, in render
    canvas = widget.render((maxcol,))
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/pudb/var_view.py", line 197, in render
    return make_canvas(text, attr, maxcol, apfx+"value")
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/pudb/ui_tools.py", line 49, in make_canvas
    line_attr = list(get_byte_line_attr(line, line_attr))
  File "/home/jordi/tmp/lol/local/lib/python2.7/site-packages/pudb/ui_tools.py", line 45, in get_byte_line_attr
    byte_count = len(line[i:i+column_count].encode(_target_encoding))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

This is on pudb version 2019.1

**Comment by inducer** [comment]
Thanks for the report. Could you take a look at #339 and see if that addresses your issue?

**Comment by jordigh** [comment]
Yes, it does, thanks! I also tested that this file also work on Python 3:

```python
#encoding: utf-8

import pudb

class X(object):
    def __repr__(self):
        return "lól"

x = X()
    
pu.db
```
