### ISSUE TITLE
tty terminal - UnicodeDecodeError: 'utf-8' codec can't decode byte (pudb/debugger.py in _runscript)

### ISSUE THREAD

**Issue by bobslee** [inducer/pudb#565]
**Describe the bug**
When debugging from a separate terminal, upon starting the debugger the following error (and traceback) occurs.

**Traceback error**

```
Traceback (most recent call last):
  File "/nix/store/hsb32260j4qr5dwwwkw1fcr9bcizf428-python3.8-pudb-2022.1.1/lib/python3.8/site-packages/pudb/__init__.py", line 148, in runscript
    dbg._runscript(mainpyfile)
  File "/nix/store/hsb32260j4qr5dwwwkw1fcr9bcizf428-python3.8-pudb-2022.1.1/lib/python3.8/site-packages/pudb/debugger.py", line 514, in _runscript
    self.run(statement)
  File "/nix/store/2fhkgfzpn8g18vinwafzxlz89pqrg0x2-python3-3.8.13/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/nix/store/2fhkgfzpn8g18vinwafzxlz89pqrg0x2-python3-3.8.13/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 40: invalid start byte
```

**To Reproduce**
1. CLI: `PUDB_TTY=/dev/pts/0 pudb3 .venv/bin/python ./my-script.py`
2. See error and traceback above

**Expected behavior**
A debugger without the error.

**Screenshot**
![image](https://user-images.githubusercontent.com/328803/196368468-89546633-d2a0-492e-9855-00509104fce9.png)

**Versions**

- version of pudb: 2022.1.1
- version of Python: 3.8 (also in 3.9)

**Comment by inducer** [comment]
`PUDB_TTY=/dev/pts/0 pudb3 .venv/bin/python ./my-script.py`

What's that `.venv/bin/python` doing there? Pudb will try to read that like a script.

**Comment by asmeurer** [comment]
If you want to run pudb from a specific python, you should use `./venv/bin/python -m pudb my_script.py`.

**Comment by bobslee** [comment]
Ok thanks!
