### ISSUE TITLE
curses.setupterm(), TypeError: argument must be an int, or have a fileno() method

### ISSUE THREAD

**Issue by aconrad** [inducer/pudb#78]
I'm using `pudb==2013.3.3`.

When I add to my code:

``` python
import pudb; pudb.set_trace()
```

I get the following traceback:

```
Traceback (most recent call last):
  File "/home/aconrad/foo/tests/server/test_jsonschema_metadata.py", line 19, in test_question_display_rule
    import pudb; pudb.set_trace()
  File "/home/aconrad/.virtualenvs/foo/local/lib/python2.7/site-packages/pudb/__init__.py", line 138, in set_trace
    dbg = _get_debugger()
  File "/home/aconrad/.virtualenvs/foo/local/lib/python2.7/site-packages/pudb/__init__.py", line 26, in _get_debugger
    dbg = Debugger(**kwargs)
  File "/home/aconrad/.virtualenvs/foo/local/lib/python2.7/site-packages/pudb/debugger.py", line 136, in __init__
    self.ui = DebuggerUI(self)
  File "/home/aconrad/.virtualenvs/foo/local/lib/python2.7/site-packages/pudb/debugger.py", line 1187, in __init__
    curses.setupterm()
TypeError: argument must be an int, or have a fileno() method.
```

I'm using the Python that is shipped with Ubuntu 13.04:

```
$ python
Python 2.7.4 (default, Apr 19 2013, 18:28:01) 
[GCC 4.7.3] on linux2
```

**Comment by inducer** [comment]
@timblaktu That sounds like an issue with urwid/termios not accepting an object it claims to accept. Could you raise an issue there?

**Comment by timblaktu** [comment]
Done. https://github.com/urwid/urwid/issues/316#issue-371763825

Thanks, @inducer.
